services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_LARAVEL=${INSTALL_LARAVEL}
    image: ${APP_NAME}-backend
    container_name: ${APP_NAME}-backend
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - backend
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    depends_on:
      - app

  database:
    image: postgres:13
    container_name: ${APP_NAME}-database
    restart: always
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${APP_NAME}-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - database

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:

